chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path("<int:study_pk>/", views.room, name="room"),
    path("review/<int:review_pk>/", views.get_review_content, name="review"),
    
    path("<int:study_pk>/delete/", views.room_delete, name="room_delete"),
    
    # for fetch
    path("<int:study_pk>/problems/", views.problems, name="problems"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/", views.reviews, name="reviews"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/<int:review_pk>/", views.review_detail, name="review_detail"),
    ]

reviews/urls.py
from django.urls import path

from . import views


app_name = 'reviews'
urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('like/', views.like, name='like'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('review_create/<int:pk>/', views.review_create, name='review_create'),
    path('review_update/<int:review_pk>/', views.review_update, name='review_update'),
    path('review_delete/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('comment_create/<int:review_pk>/', views.comment_create, name='comment_create'),
    path('comment_update/<int:comment_pk>/', views.comment_update, name='comment_update'),
    path('comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]

studies/urls.py
from django.urls import path
from . import views


app_name = 'studies'
urlpatterns = [
    # 스터디 CRUD
    path('', views.index, name='index'),
    path('<int:study_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:study_pk>/delete/', views.delete, name='delete'),
    path('<int:study_pk>/update/', views.update, name='update'),
    # 스터디 join_conditoin 변경
    path('<int:study_pk>/condition/<int:condition_num>/', views.condition, name='condition'),
    
    # 스터디 가입 요청 관련 {POST}
    path('<int:study_pk>/join/', views.join, name='join'), # 스터디 가입, 가입 요청
    path('<int:study_pk>/withdraw/', views.withdraw, name='withdraw'), # 스터디 탈퇴
    path('<int:study_pk>/accept/<username>/', views.accept, name='accept'), # 스터디 가입 요청 수락
    path('<int:study_pk>/reject/<username>/', views.reject, name='reject'), # 스터디 가입 요청 거절
    path('<int:study_pk>/expel/<username>/', views.expel, name='expel'), # 스터디원 방출
    path('<int:study_pk>/cancel/', views.cancel, name='cancel'), # 스터디 가입 요청 취소
  
    # 메인보드
    path('<int:study_pk>/mainboard/', views.mainboard, name='mainboard'),
    path('<int:study_pk>/mainboard/member/', views.member, name='member'),
    path('<int:study_pk>/mainboard/problem/', views.problem, name='problem'),
    path('<int:study_pk>/mainboard/problem/search/', views.problem_search, name='problem_search'),

    # 스터디 공지 in 메인보드
    path('<int:study_pk>/mainboard/announcement/', views.announcement, name='announcement'),
    path('<int:study_pk>/mainboard/announcement/create/', views.announcement_create, name='announcement_create'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/', views.announcement_detail, name='announcement_detail'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/update/', views.announcement_update, name='announcement_update'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/delete/', views.announcement_delete, name='announcement_delete'),
    
    # 스터디장 (Studying.permission) 임명(appoint), 해임(dismiss)
    # 부스터디장?
    path('<int:study_pk>/appoint/<username>/<int:permission>/', views.appoint, name='appoint'),
    path('<int:study_pk>/dismiss/<username>/', views.dismiss, name='dismiss'),
    
    # 스터디 댓글
    path('<int:study_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:study_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:study_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

reviews/models.py
from django.conf import settings
from django.db import models, transaction
# from django.urls import reverse_lazy
from taggit.managers import TaggableManager


# Create your models here.
class Problem(models.Model):
    post_num = models.IntegerField('글 번호')
    title = models.CharField('제목', max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='게시자', on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_problems')
    
    # url shortener + 미리보기 + Validator
    url = models.URLField('문제 링크', max_length=1000)
    tags = TaggableManager(blank=True, related_name='problem_set')
    description = models.TextField('설명')

    study = models.ForeignKey("studies.Study", verbose_name='스터디', on_delete=models.CASCADE, default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'problem'


    def __str__(self) -> str:
        return self.title

    @transaction.atomic
    def save(self, *args, **kwargs):
        self.post_num = self.study.post_index
        self.study.post_index = models.F('post_index') + 1
        self.study.save()
        super().save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse_lazy('reviews:detail', kwargs={'pk': self.pk})


class Review(models.Model):
    content = models.TextField('내용')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='작성자', on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    problem = models.ForeignKey("reviews.Problem", verbose_name='문제', on_delete=models.CASCADE)
    tags = TaggableManager(blank=True, related_name='review_set')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'review'


    def __str__(self) -> str:
        return f'Review by {self.user}, on {self.problem}'


class Comment(models.Model):
    content = models.TextField('내용')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='작성자', on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    review = models.ForeignKey("reviews.Review", verbose_name='리뷰', on_delete=models.CASCADE)
    # tags = TaggableManager(blank=True, related_name='comment_set')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'comment'

    def __str__(self) -> str:
        return f'Comment by {self.user}, on {self.review}'

reviews/forms.py
from django import forms
from taggit.forms import TagWidget, TagField

from .models import Problem, Review, Comment
    

class ProblemForm(forms.ModelForm):
    '''
    태그 help_text 한 곳에서 관리하기
    '''
    tags = TagField(
        required=False,
        widget=TagWidget,
        help_text='태그를 입력하세요. 공백문자로 태그를 구분하며 대소문자를 구분하지 않습니다.',
    )
    class Meta:
        model = Problem
        fields = (
            'title',
            'tags',
            'description',
        )


class ReviewForm(forms.ModelForm):
    tags = TagField(
        required=False,
        widget=TagWidget,
        help_text = '태그를 입력하세요. 공백문자로 태그를 구분하며 대소문자를 구분하지 않습니다.',
    )
    class Meta:
        model = Review
        fields = (
            'tags',
            'content',
        )


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content',)

reviews/views.py
import json
import operator
import logging
from functools import reduce
from typing import Any

from django.http import JsonResponse, Http404, QueryDict
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q, Prefetch
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.db import transaction

from taggit.models import Tag

from .forms import ProblemForm, ReviewForm, CommentForm
from .models import Problem, Review, Comment
from .utils import render, HttpResponse, HTTPResponseHXRedirect

from studies.models import Study


# 로깅 설정
logger = logging.getLogger(__name__)


# Create your views here.
@login_required
def detail(request, pk):
    '''
    42 queries in 14.26ms → 31 queries in 13.03ms
    '''
    problem = get_object_or_404(
        Problem.objects.prefetch_related(
            'tags',
            Prefetch(
                'review_set', 
                queryset=Review.objects.prefetch_related(
                    'tags',
                    Prefetch(
                        'comment_set',
                        queryset=Comment.objects.select_related('user').prefetch_related('like_users'),
                    ),
                ).select_related('user').prefetch_related('like_users'),
            ),
        ).select_related('study', 'user'),
        pk=pk
    )

    if not problem.study.studying_users.filter(username=request.user).exists():
        return redirect('studies:detail', problem.study.pk)
    
    querydict = {
        'problem': Q(problem_set=pk),
        'review': Q(review_set__in=problem.review_set.values('id')),
    }

    tags = Tag.objects.filter(reduce(operator.__or__, querydict.values()))
    tags = tags.annotate(freq=Count('name'))
    ordered_tags = tags.order_by('-freq').values('name')

    context = {
        'problem': problem,
        'tags': ordered_tags.values(),
        'study' : problem.study
    }
    return render(request, 'reviews/detail.html', context)


@require_http_methods(['GET', 'POST'])
@login_required
def create(request):
    study_id = request.GET.get('study', request.session.get('study_id'))
    member = get_object_or_404(
        Study, pk=study_id,
    ).studying_users.filter(username=request.user).exists()
    
    if study_id is None or not member:
        return redirect('studies:detail', study_id)
    
    request.session['study_id'] = study_id
    
    if request.method == 'POST':
        form = ProblemForm(data=request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            problem.user, problem.study = request.user, get_object_or_404(Study, pk=study_id)
            problem.save()
            form.save_m2m()
            return redirect('reviews:detail', problem.pk)

        return redirect('studies:mainboard', study_id)
    else:
        form = ProblemForm()
    context = {
        'form': form,
    }
    return render(request, 'reviews/create.html', context)


@require_http_methods(['GET', 'PUT'])
@login_required
def update(request, pk):
    problem = get_object_or_404(Problem.objects.select_related('study'), pk=pk)
    
    if request.user != problem.user:
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': pk}))
    
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        form = ProblemForm(data, instance=problem)
        if form.is_valid():
            updated_form = form.save(commit=False)
            updated_form.save()
            form.save_m2m()
            return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': pk}))
    else:
        form = ProblemForm(instance=problem)
    context = {
        'form': form,
    }
    return render(request, 'reviews/update.html', context)


@require_http_methods(['DELETE'])
@login_required
def delete(request, pk):
    problem = get_object_or_404(
        Problem.objects.select_related('study'), pk=pk,
    )
    study_pk = problem.study.pk

    if request.user == problem.user:
        problem.delete()
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('studies:mainboard', kwargs={'study_pk':study_pk}))
    return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': pk}))
    

@require_http_methods(['GET', 'POST'])
@login_required
def review_create(request, pk):
    problem = get_object_or_404(
        Problem.objects.select_related('study'),
        pk=pk,
    )
    
    if not problem.study.studying_users.filter(username=request.user).exists():
        return redirect('studies:detail', problem.study.pk)
    
    if request.method == 'POST':
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user, review.problem = request.user, problem
            review.save()
            form.save_m2m() 

            # 유저의 experience를 10 증가시킴
            with transaction.atomic():
                user = request.user
                user.experience += 10
                user.save()


            context = {
                'problem': Problem.objects.get(pk=pk)
            }
            return redirect('reviews:detail', review.problem.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'problem_pk': pk,
    }
    return render(request, 'reviews/review_create.html', context)


@require_http_methods(['GET', 'PUT'])
@login_required
def review_update(request, review_pk):
    review = get_object_or_404(
        Review.objects.select_related('problem__study'),
        pk=review_pk,
    )
    study_pk = review.problem.study.pk
    if not review.problem.study.studying_users.filter(username=request.user).exists():
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('studies:detail', kwargs={'study_pk': study_pk}))
    
    if request.user != review.user:
        return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': review.problem.pk}))
    
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        form = ReviewForm(data, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.save()
            form.save_m2m()
            return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': review.problem.pk}))
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
    }
    return render(request, 'reviews/review_update.html', context)


@require_http_methods(['DELETE'])
@login_required
def review_delete(request, review_pk):
    review = get_object_or_404(
        Review.objects.select_related('problem__study'),
        pk=review_pk
    )
    problem_pk = review.problem.pk
    if request.user == review.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, "리뷰가 성공적으로 삭제되었습니다.")
    return HTTPResponseHXRedirect(redirect_to=reverse_lazy('reviews:detail', kwargs={'pk': problem_pk}))


@require_http_methods(['GET', 'POST'])
@login_required
def comment_create(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user, comment.review = request.user, review
            comment.save()

            # 작성한 유저에게 5의 경험치 추가
            comment.user.experience += 5
            comment.user.save()
            context = {
                'review': Review.objects.prefetch_related('comment_set__user').get(pk=review_pk),
            }
            trigger = json.dumps({
                'clear-textarea': {
                    'textarea_id': f'comment-textarea-{review.pk}',
                }, 
                'recount': {
                    'counter_id': f'comment-count-Review-{review.pk}',
                    'count': review.comment_set.count(),
                }
            })
            return render(request, 'reviews/comments/list.html', context, trigger=trigger)
        return render(request, 'reviews/comments/list.html', context)
    else:
        form = CommentForm()
    context = {
        'comment_form': form,
        'review': review,
    }
    return render(request, 'reviews/comments/create.html', context)


@require_http_methods(['GET', 'PUT'])
@login_required
def comment_update(request, comment_pk):
    comment = get_object_or_404(
        Comment.objects.select_related('review'),
        pk=comment_pk
    )
    context = {
        'comment': comment,
        'review': comment.review,
    }    
    if request.user != comment.user:
        return render(request, 'reviews/comments/item.html', context)
    
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        form = CommentForm(data=data, instance=comment)
        if form.is_valid():
            form.save()
            return render(request, 'reviews/comments/item.html', context)
        context['comment_form'] = form
        return render(request, 'reviews/comments/list.html', context)
    else:
        context['comment_form'] = CommentForm(instance=comment)
    return render(request, 'reviews/comments/update.html', context)


@require_http_methods(['DELETE'])
@login_required
def comment_delete(request, comment_pk):
    comment = get_object_or_404(
        Comment.objects.select_related('review'),
        pk=comment_pk
    )
    review = comment.review
    context = {
        'review': review
    }
    if request.user == comment.user:
        comment.delete()
        trigger = json.dumps({
            'recount': {
                'counter_id': f'comment-count-Review-{review.pk}',
                'count': review.comment_set.count(),
            }
        })

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block head %}
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism.min.css"
  />
  <link
    rel="stylesheet"
    href="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight.min.css"
  />
{% endblock head %}

{% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/reviews/create.css' %}"
/>
{% endblock style %}
{% block content %}
<div class="main__container">
  <form id="form" action="{% url 'reviews:create' %}" method="post">
    {% csrf_token %}
    
    {% with form.title as title %}
    <div class="form-group">
      <label for="{{ title.id_for_label }}">{{ title.label }}</label>
      <input type="{{ title.field.widget.input_type }}" class="form-control" id="" placeholder="{{ title.label }}" name="{{ title.name }}" />
    </div>
    {% endwith %}

    {% with form.description as description %}
    <div class="form-group" style="display: none;">
      {# UI에 드러나지 않는 div입니다 #}
      <label for="{{ description.id_for_label }}">{{ description.label }}</label>
      <textarea id="{{ description.id_for_label }}" class="form-control" placeholder="{{ description.label }}" name="{{ description.name }}"></textarea>
    </div>
    {% endwith %}
    
    {# ToastUI가 들어가는 div입니다 #}
    <div id="editor"></div>

    {% with form.tags as tags %}
    <div class="form-group">
      <label for="{{ tags.id_for_label }}">{{ tags.label }}</label>
      <input type="{{ tags.field.widget.input_type }}" class="form-control" id="{{ tags.id_for_label }}" placeholder="{{ tags.label }}" name="{{ tags.name }}" />
    </div>
    <p class="help-text">{{ tags.help_text }}</p>
    {% endwith %}
    <button class="submit-button button-small" type="submit">문제 등록하기</button>
  </form>
</div>

<script src="{% static 'reviews/toastui.js' %}"></script>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block head %}
{% endblock head %}

{% block style %}
<link
rel="stylesheet"
type="text/css"
href="{% static 'CSS/reviews/detail.css' %}"
/>
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism.min.css"
/>
<link
  rel="stylesheet"
  href="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight.min.css"
/>

{% endblock style %} 
{% block content %}
<div class="main__container">
  <div style="margin-right: auto;">
    <a href="{% url 'studies:mainboard' study.pk %}" class="homebutton button-small">< MAINBOARD</a>
    {% comment %} {% if request.user in study.studying_users.all %} {% endcomment %}
    {% comment %} <a href="{% url 'studies:mainboard' study.pk %}"><p class="mainboardbutton button-small">MAINBOARD ></p></a> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
  </div>
  <div class="probelm-box">
    <hgroup>
      <h1 class="problem-title">{{ problem.title }}</h1>
      <div class="study__userInfo">
        <div class="study__userInfo-badge">
          <p>{{ problem.user.emoji }}</p>
        </div>
        <div class="study__userInfo-username">{{ problem.user }}</div>
      </div>
    </hgroup>
    <div class="problem__info">
      <i class="bi bi-hand-thumbs-up"><span id="like-count-{{ problem|id }}">{{problem.like_users.count}}</span></i>
      <i id="review-count-{{ problem|id }}" class="bi bi-code-square"><span>{{problem.review_set.all.count}}</span></i>
    </div>
    <div class="study__crudInfo">
      {{ problem.created_at }}
      {# 스터디 수정/삭제 #}
      {% if request.user == problem.user %}
      <a
        class="study__crudInfo-item"
        href="{% url 'reviews:update' problem.pk %}"
        >수정</a
      >
      <button hx-delete="{% url 'reviews:delete' problem.pk %}" hx-confirm="문제를 삭제하시겠습니까?" class="study__crudInfo-item">삭제</button>
      {% endif %}
      
    </div>
    <hr>
    {# TODO: 좋아요 수정 #}
    {% include 'reviews/components/like.html' with obj=problem %}
    <div class="probelm-content-box">
      <div id="viewer">{{ problem.description|json_script:'problem_description' }}</div>
    </div>
    <div class="problem-tag__container">
      {% for tag in problem.tags.all|dictsort:'name' %}
        <form id="form-{{ tag }}" class="tag-form" action="{% url 'studies:problem_search' problem.study.pk %}">
          <input type="hidden" name="tags" value="{{ tag.name }}">
          <button type="submit" class="tag-item">#{{ tag }}</button>
        </form>
      {% endfor %}

    </div>
    <hr>

    <div class="submit-button__container">
      <a href="{% url 'reviews:review_create' problem.pk %}" class="button-small joinbutton reset-style">게시글 등록하기</a>
    </div>
  </div>

  {# 코드 #}
  <ul class="review__container">
    {% if problem.review_set.all %}
    {% for review in problem.review_set.all|sort_by_likes %}
    <div class="review-content" id="myCode-{{ review.user.id }}">
      <div class="study__userInfo">
        <div class="study__userInfo-badge">
          <p>{{ review.user.emoji }}</p>
        </div>
        <div class="study__userInfo-username">{{ review.user }}</div>
      </div>
      <div class="problem__info review__info">
        <i class="bi bi-hand-thumbs-up"><span id="like-count-{{ review|id }}">{{review.like_users.count}}</span></i>
        <i class="bi bi-chat-dots"><span id="comment-count-{{ review|id }}">{{review.comment_set.count}}</span></i>
      </div>
      <div class="study__crudInfo">
        {{ review.created_at }}
        {# 코드 수정/삭제 #}
        {% if request.user == review.user %}
        <a
          class="study__crudInfo-item"
          href="{% url 'reviews:review_update' review.pk %}"
          >수정</a
        >
        <button hx-delete="{% url 'reviews:review_delete' review.pk %}" hx-confirm="문제를 삭제하시겠습니까?" class="study__crudInfo-item">삭제</button>
        {% endif %}
      </div>
      <hr>
      {% include 'reviews/components/like.html' with obj=review %}
      <div id="reviewViewer">{{ review.content|json_script:'review.content' }}</div>
      <div class="review-tag__container">
        {% for tag in review.tags.all|dictsort:'name' %}
        <a href="">
          <span class="tag-item">#{{ tag }}</span>
        </a>
        {% endfor %}
      </div>
      <hr>
      <section class="comment-section">
        {# 버튼 클릭시 아래에 댓글 작성창이 생성됩니다. #}
        <div id="create-comment-on-{{ review.pk }}" hx-target="this" hx-swap="outerHTML" class="d-flex flex-row-reverse">
          <button id="add-comment-btn-{{ review.pk }}" hx-get="{% url 'reviews:comment_create' review.pk %}" class="button-small joinbutton">댓글 쓰기</button>
        </div>
        <div class="comments__wrapper">
          <ul id="comment-list-{{ review.pk }}" hx-swap="outerHTML">
            {% include 'reviews/comments/list.html' with obj=comment %}
          </ul>
        </div>
      </div>
    </section>
    {% endfor %}
    {% else %}
    <div class="null-message">🐲 문제에 코드를 등록해보세요!</div>
    {% endif %}

  </ul>
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'reviews/like.js' %}"></script>
<script src="{% static 'reviews/toastViewer.js' %}"></script>

<script>
  const tagForms = document.querySelectorAll('.tag-form');
  tagForms.forEach((form) => {
  form.addEventListener('submit', (event) => {
    event.preventDefault();

    const tag = form.querySelector('input[name="tags"]').value;
    searchProblemsByTag(tag);
    });
  });

  function searchProblemsByTag(tag) {
    fetch(`http://127.0.0.1:8000/studies/{{ problem.study.pk }}/mainboard/problem/search?tags=${encodeURIComponent(tag)}`)
      .then(response => response.json())
      .then(data => {
        console.log(data.problems)
      })
      .catch(error => {
        console.error('Error:', error);
      });
  }

</script>

<script src="{% static 'reviews/countComment.js' %}"></script>

{% endblock content %}

reviews/templates/reviews/review_create.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/themes/prism.min.css"
  />
  <link
    rel="stylesheet"
    href="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight.min.css"
  />
{% endblock head %}
{% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/reviews/create.css' %}"
/>
{% endblock style %}
{% block content %}
<div class="main__container">
<form id="form" action="{% url 'reviews:review_create' problem_pk %}" method="post">
  {% csrf_token %}
  
  {% with form.content as content %}
  <div class="form-group" style="display: none;">
    {# UI에 드러나지 않는 div입니다 #}
    <label for="{{ content.id_for_label }}">{{ content.label }}</label>
    <textarea id="{{ content.id_for_label }}" class="form-control" placeholder="{{ content.label }}" name="{{ content.name }}"></textarea>
  </div>
  {% endwith %}
  
  {# ToastUI가 들어가는 div입니다 #}
  <div id="editor"></div>

  {% with form.tags as tags %}
  <div class="form-group">
    <label for="{{ tags.id_for_label }}">{{ tags.label }}</label>
    <input type="{{ tags.field.widget.input_type }}" class="form-control" id="" placeholder="{{ tags.label }}" name="{{ tags.name }}" />
  </div>
  {% endwith %}
  
  <button class="submit-button button-small" type="submit">리뷰 작성하기</button>
</form>
</div>
<script src="{% static 'reviews/toastui.js' %}"></script>
{% endblock content %}