chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path("<int:study_pk>/", views.room, name="room"),
    path("review/<int:review_pk>/", views.get_review_content, name="review"),
    
    path("<int:study_pk>/delete/", views.room_delete, name="room_delete"),
    
    # for fetch
    path("<int:study_pk>/problems/", views.problems, name="problems"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/", views.reviews, name="reviews"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/<int:review_pk>/", views.review_detail, name="review_detail"),
    ]

reviews/urls.py
from django.urls import path

from . import views


app_name = 'reviews'
urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('like/', views.like, name='like'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('review_create/<int:pk>/', views.review_create, name='review_create'),
    path('review_update/<int:review_pk>/', views.review_update, name='review_update'),
    path('review_delete/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('comment_create/<int:review_pk>/', views.comment_create, name='comment_create'),
    path('comment_update/<int:comment_pk>/', views.comment_update, name='comment_update'),
    path('comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]

studies/urls.py
from django.urls import path
from . import views


app_name = 'studies'
urlpatterns = [
    # 스터디 CRUD
    path('', views.index, name='index'),
    path('<int:study_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:study_pk>/delete/', views.delete, name='delete'),
    path('<int:study_pk>/update/', views.update, name='update'),
    # 스터디 join_conditoin 변경
    path('<int:study_pk>/condition/<int:condition_num>/', views.condition, name='condition'),
    
    # 스터디 가입 요청 관련 {POST}
    path('<int:study_pk>/join/', views.join, name='join'), # 스터디 가입, 가입 요청
    path('<int:study_pk>/withdraw/', views.withdraw, name='withdraw'), # 스터디 탈퇴
    path('<int:study_pk>/accept/<username>/', views.accept, name='accept'), # 스터디 가입 요청 수락
    path('<int:study_pk>/reject/<username>/', views.reject, name='reject'), # 스터디 가입 요청 거절
    path('<int:study_pk>/expel/<username>/', views.expel, name='expel'), # 스터디원 방출
    path('<int:study_pk>/cancel/', views.cancel, name='cancel'), # 스터디 가입 요청 취소
  
    # 메인보드
    path('<int:study_pk>/mainboard/', views.mainboard, name='mainboard'),
    path('<int:study_pk>/mainboard/member/', views.member, name='member'),
    path('<int:study_pk>/mainboard/problem/', views.problem, name='problem'),
    path('<int:study_pk>/mainboard/problem/search/', views.problem_search, name='problem_search'),

    # 스터디 공지 in 메인보드
    path('<int:study_pk>/mainboard/announcement/', views.announcement, name='announcement'),
    path('<int:study_pk>/mainboard/announcement/create/', views.announcement_create, name='announcement_create'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/', views.announcement_detail, name='announcement_detail'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/update/', views.announcement_update, name='announcement_update'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/delete/', views.announcement_delete, name='announcement_delete'),
    
    # 스터디장 (Studying.permission) 임명(appoint), 해임(dismiss)
    # 부스터디장?
    path('<int:study_pk>/appoint/<username>/<int:permission>/', views.appoint, name='appoint'),
    path('<int:study_pk>/dismiss/<username>/', views.dismiss, name='dismiss'),
    
    # 스터디 댓글
    path('<int:study_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:study_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:study_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

studies/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from datetime import datetime, timedelta
from django.utils import timezone
from django.http import JsonResponse
from django.core.paginator import Paginator, Page

from taggit.models import Tag
from django.db.models import Count, Q
from reviews.models import Problem, Review
from .models import Study, Studying, Announcement, AnnouncementRead, StudyComment
from .forms import StudyForm, AnnouncementForm, StudyCommentForm
from .models import LANGUAGE_CHOICES
import re


# Create your views here.
def index(request):
    query = request.GET.get('query')
    category = request.GET.get('category')
    if query:
        studies = Study.objects.filter(
            Q(title__icontains=query)|Q(user__username__iexact=query)|
            Q(category__name__iexact=query)|Q(language__icontains=query)
            ).annotate(
            member_num=Count('studying_users')
            ).order_by('-created_at')
    elif category:
        studies = Study.objects.filter(
            category__name__iexact=category
            ).annotate(
            member_num=Count('studying_users')
            ).order_by('-created_at')
    else:
        studies = Study.objects.annotate(
            member_num=Count('studying_users')
            ).order_by('-created_at')
    
    selected_langs = request.GET.get('lang')
    is_recruit = request.GET.get('recruits')
    if is_recruit == 'true':
        studies = studies.filter(is_recruiting=1)

    if selected_langs:
        selected_langs_list = selected_langs.split(',') 
        filter_query = Q()
        for lang in selected_langs_list:
            filter_query |= Q(language__regex=r'\b{}\b'.format(re.escape(lang.strip())))
        studies = studies.filter(filter_query).distinct()
        # print(studies)
    
    if category :
        studies = studies.filter(category__name__iexact=category)

    context = {
        'studies': studies,
        'LANGUAGE_CHOICES' : LANGUAGE_CHOICES,
    }
    return render(request, 'studies/index.html', context)


def detail(request, study_pk: int):
    study = get_object_or_404(Study, pk=study_pk)
    
    # 현재 스터디 가입 여부 is_studying
    if study.studying_users.filter(pk=request.user.pk).exists():
        # 스터디 가입
        is_studying = 'joined'
    elif study.join_request.filter(pk=request.user.pk).exists():
        is_studying = 'join_request'
    else:
        # 스터디 미가입
        is_studying = 'not_joined'
        
    comment_form = StudyCommentForm()
    comments = study.studycomment_set.all()
    
    context = {
        'study': study,
        'is_studying': is_studying,
        'LANGUAGE_CHOICES': LANGUAGE_CHOICES,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'studies/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = StudyForm(data=request.POST)
        if form.is_valid():
            study = form.save(commit=False)
            study.user = request.user
            if study.join_condition == 3:
                study.is_recruiting = 2
                
            study.save()
            
            # Tag 저장
            form.save_m2m()
            
            # 스터디장 권한(permission) 3으로 Studying 테이블에 추가
            Studying.objects.create(study=study, user=request.user, permission=3)
            
            return redirect('studies:detail', study.pk)
    else:
        form = StudyForm()
        
    context = {
        'form': form,
    }
    return render(request, 'studies/create.html', context)


def update(request, study_pk: int):
    study = get_object_or_404(Study, pk=study_pk)
    
    # 스터디장만 수정 가능
    if request.user != study.user:
        return redirect('studies:detail', study_pk)
    
    if request.method == 'POST':
        form = StudyForm(data=request.POST, instance=study)
        if form.is_valid():
            # taggit을 위해 commit=False 후 save_m2m()
            study = form.save(commit=False)
            # 스터디 가입 조건-가입 불가로 변경시 모든 가입 요청 삭제, 모집 마감
            if study.join_condition == 3:
                study.join_request.clear()
                study.is_recruiting = 2

            # 스터디 정원 늘어난 경우 - 가입 불가 상태가 아니고, 기존에 모집 마감상태였다면 모집 중으로 다시 변경
            if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] < study.capacity and study.join_condition != 3 and study.is_recruiting == 2:
                study.is_recruiting = 1
            # 스터디 정원을 현재 인원만큼 줄인 경우 - 가입 불가 상태가 아니고, 기존에 모집 중 상태였다면 모집 마감으로 다시 변경
            elif Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] == study.capacity and study.join_condition != 3 and study.is_recruiting == 1:
                study.is_recruiting = 2
            
            study.save()
            form.save_m2m()
            
            return redirect('studies:detail', study_pk)
    else:
        form = StudyForm(instance=study)
        
    context = {
        'study_pk': study_pk,
        'form': form,
    }
    return render(request, 'studies/update.html', context)


def delete(request, study_pk: int):
    study = get_object_or_404(Study, pk=study_pk)
    
    # 스터디장만 삭제 가능
    if request.user == study.user:
        try:
            study.delete()
            return redirect('/')
        finally:
            Tag.objects.annotate(ntag=Count('taggit_taggeditem_items')).filter(ntag=0).delete()
        
    
    return redirect('studies:index')


# 스터디 가입 및 가입 요청
@login_required
def join(request, study_pk: int):
    study = get_object_or_404(Study, pk=study_pk)
    me = request.user
    
    # 스터디 인원 만원 시 승낙 불가
    if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] >= study.capacity:
        print('Error: 스터디 만원')
        return redirect('studies:detail', study_pk)
    
    # User가 스터디에 가입되어 있지 않은 경우
    if not Studying.objects.filter(study=study, user=me).exists():
        # 1 : 승인 필요, 2: 즉시 가입, 3: 가입 불가
        if study.join_condition == 2:
            # Studying.objects.create(study=study, user=me)
            study.studying_users.add(me)
            # AnnouncementRead 공지 읽음 여부 테이블에 추가
            for announcement in study.announcements.all():
                announcement.announcement_reads.add(me)

            # 스터디장 경험치 10 추가
            study.user.experience += 10
            study.user.save()

        elif study.join_condition == 1:
            study.join_request.add(me)
        # join_condition == 3 - 가입불가
    
    # 가입 후 스터디 인원 만원 시 모집 마감
    if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] >= study.capacity:
        study.is_recruiting = 2
        study.save()

    return redirect('studies:detail', study_pk)
    

# 스터디 탈퇴
@login_required
def withdraw(request, study_pk: int):
    study = get_object_or_404(Study, pk=study_pk)
    me = request.user
    
    if study.studying_users.filter(pk=me.pk).exists():
        # 스터디장 탈퇴 불가
        if me != study.user:
            study.studying_users.remove(me)
    
    # 탈퇴 후에 정원이 남아있고, 가입 불가 상태가 아니고, 모집 마감상태라면 모집 중으로 다시 변경
    if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] < study.capacity and study.join_condition != 3 and study.is_recruiting == 2:
        study.is_recruiting = 1
        study.save()
        
    return redirect('studies:detail', study_pk)


# 스터디 가입 요청 시 수락
@login_required
def accept(request, study_pk: int, username: int):
    study = get_object_or_404(Study, pk=study_pk)
    person = get_user_model().objects.get(username=username)
    me = request.user
    
    # Study 가입 조건-가입 불가 시 가입 요청 승인 불가
    if study.join_condition == 3:
        return redirect('studies:detail', study_pk)
        
    # 스터디 인원 만원 시 승낙 불가
    if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] >= study.capacity:
        print('Error: 스터디 만원')
        return redirect('studies:detail', study_pk)
    
    # 스터디장 혹은 부스터디장(permission > 1)인 유저만 요청 허가 가능
    if Studying.objects.filter(study=study, user=me, permission__gte=2).exists():
        Studying.objects.get_or_create(study=study, user=person)
        for announcement in study.announcements.all():
            announcement.announcement_reads.add(person)
        study.join_request.remove(person)
        
        # 스터디장 경험치 10 추가
        study.user.experience += 10
        study.user.save()
    
    # 가입 후 스터디 인원 만원 시 모집 마감
    if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] >= study.capacity:
        study.is_recruiting = 2
        study.save()

    return redirect('studies:mainboard', study_pk)

# 스터디 가입 요청 시 거절
@login_required
def reject(request, study_pk: int, username: int):
    study = get_object_or_404(Study, pk=study_pk)
    person = get_user_model().objects.get(username=username)
    me = request.user
    
    # 스터디장 혹은 부스터디장(permission > 1)인 유저만 스터디 가입 요청 거절
    if Studying.objects.filter(study=study, user=me, permission__gte=2).exists():
        study.join_request.remove(person)
    
    return redirect('studies:mainboard', study_pk)


# 스터디에서 해당 유저 방출
@login_required
def expel(request, study_pk: int, username: int):
    study = get_object_or_404(Study, pk=study_pk)
    person = get_user_model().objects.get(username=username)
    me = request.user
    
    # 스터디장인 유저만 스터디원 방출 가능
    if Studying.objects.filter(study=study, user=me, permission__gte=2).exists():
        studying = Studying.objects.filter(study=study, user=person)
        if studying.first().permission <= 2:
            studying.first().delete()
    

    # 방출 후에 정원이 남아있고, 가입 불가 상태가 아니고, 모집 마감상태라면 모집 중으로 다시 변경
        if Studying.objects.filter(study=study).aggregate(cnt=Count('*'))['cnt'] < study.capacity and study.join_condition != 3 and study.is_recruiting == 2:
            study.is_recruiting = 1
            study.save()

    return redirect('studies:detail', study_pk)


# 스터디 가입 요청 취소

studies/templates/studies/announcement_detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/studies/announcement/detail.css' %}"
/>
{% endblock style %}
{% block title %}{{ announcement.study }}의 공지사항{% endblock title %}


{% block content %}
<div class="main__container">
  <a class="study-title" href="{% url 'studies:mainboard' study_pk %}">
    < {{ announcement.study }}
  </a>
  <a href="{% url 'studies:announcement' study_pk %}">
    <h1>📢 공지사항</h1>
  </a>
  <p class="title">{{ announcement.title }}
    <div class="date">
      <p>{{ announcement.created_at }}</p>
    </div>
  </p>
  <div class="content-box">
    <p class="content">{{ announcement.content|linebreaksbr }}</p>
  </div>
  <div class="button-box">
    {% if request.user == leader %}
    <a href="{% url 'studies:announcement_update' study_pk announcement.pk %}">
      <div class="button button-small">공지 수정</div>
    </a>
    <form action="{% url 'studies:announcement_delete' study_pk announcement.pk %}" method="post">
      {% csrf_token %}
      <button class="button button-small" type="submit">공지 삭제</button>
    </form>
    {% endif %}
    {% comment %} <a href="{% url 'studies:announcement' study_pk %}">
      <div class="button button-small list">공지 목록으로</div>
    </a> {% endcomment %}
  </div>
</div>
{% endblock content %}

studies/templates/studies/detail.html
{% extends 'base.html' %} {% load static %} {% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/studies/detail.css' %}"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/comment.css' %}"
/>
{% endblock style %}
{% block content %}

<main class="study__wrapper">
  <div style="display:flex; justify-content:space-between; align-items:center;">
    <a href="{% url 'main' %}" class="homebutton button-small">< HOME</a>
    {% if request.user in study.studying_users.all %}
    <a href="{% url 'studies:mainboard' study.pk %}"><p class="mainboardbutton button-small">MAINBOARD ></p></a>
    {% endif %}
  </div>
  {# 스터디 디테일 내용 #}
  <article>
    <div class="study__container">
      <div class="study__title">{{ study.title }}</div>
      <div class="study__userInfo">
        <div class="study__userInfo-badge">
          <p>{{ study.user.emoji }}</p>
        </div>
        <div class="study__userInfo-username">{{ study.user }}</div>
      </div>
      <div class="study__crudInfo">
        {{ study.created_at }}
        {# 스터디 수정/삭제 #}
        {% if request.user == study.user %}
        <a
          class="study__crudInfo-item"
          href="{% url 'studies:update' study.pk %}"
          >수정</a
        >
        <button
          type="button"
          data-bs-toggle="modal"
          data-bs-target="#deleteStudy"
          class="study__crudInfo-item"
        >
          삭제
        </button>

        {# 삭제 모달 #}
        <div
          class="modal fade"
          id="deleteStudy"
          tabindex="-1"
          aria-labelledby="deleteStudyLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog">
            <div class="modal-content pt-3 px-3">
              <button
                type="button"
                class="btn-close ms-auto"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
              <div class="modal-body text-center">정말 삭제하시겠습니까?</div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  닫기
                </button>
                {# 삭제 버튼 #}
                <form
                  action="{% url 'studies:delete' study.pk %}"
                  method="post"
                >
                  {% csrf_token %}
                  <button type="submit" class="btn btn-delete">삭제</button>
                </form>
                {# 삭제 버튼 end #}
              </div>
            </div>
          </div>
        </div>
        {# 삭제 모달 end #}
        {% endif %}
        {# 스터디 수정/삭제 end #}
      </div>
      <hr />

      <div class="study__info">
        <div class="study__info-item">
          <div class="study__info-item-left">
            <div class="study__info-item-title">모집 인원</div>
            <div class="separator"></div>
          </div>
          <div class="study__info-item-right">
            {{study.studying_users.count}}/{{ study.capacity }}
          </div>
        </div>
        <div class="study__info-item">
          <div class="study__info-item-left">
            <div class="study__info-item-title">스터디 일정</div>
            <div class="separator"></div>
          </div>
          <div class="study__info-item-right study__info-margin-top">
            {# 요일 #}
            {% if study.days %}
            {% for day in study.days %} 
            <div class="study__info-circle">{{ day }}</div>
            {% endfor %}
            {% else %}
            <div class="cancel-margintop">
              요일 미정
            </div>
            {% endif %}
            
            {# 시간 #}
            <div class="study-time__container">
              {% if study.start_time %}
                {% if study.end_time %}
                  {{ study.start_time }} ~ {{ study.end_time }}
                {% else %}
                  {{ study.start_time }} ~ 미정
              {% endif %}
              {% else %}
                {% if study.end_time %}
                  미정 ~ {{ study.end_time }}
                  {% else %}
                    {% if study.days%}
                    시간 미정
                    {% else %}
                    {% endif %}
                {% endif %}
              {% endif %}
          </div>
          </div>
        </div>
        <div class="study__info-item">
          <div class="study__info-item-left">
            <div class="study__info-item-title">스터디 기간</div>
            <div class="separator"></div>
          </div>
          <div class="study__info-item-right">
            {% if study.start_date %}
              {% if study.end_date %}
                {{ study.start_date }} ~ {{ study.end_date }}
              {% else %}
                {{ study.start_date }} ~ 미정
              {% endif %}
            {% else %}
              {% if study.end_date %}
                미정 ~ {{ study.end_date }}
              {% else %}
                미정
              {% endif %}
            {% endif %}
          </div>
        </div>
        <div class="study__info-item">
          <div class="study__info-item-left">
            <div class="study__info-item-title">알고리즘 언어</div>
            <div class="separator"></div>
          </div>
          <div class="study__info-item-right study__info-margin-top"> 
            {% if study.language %}
              {% for language in study.language %}
              {% for lang_code, lang_name in LANGUAGE_CHOICES %}
              {% if lang_code == language %}
                <div class="study__info-circle custom-circle">
                  <div class="lauguage__container">
                    <div>{{ lang_name }}</div>
                  </div>
                </div>
              {% endif %}
              {% endfor %}
              {% endfor %}
            {% else %}
              <div class="cancel-margintop">
                미정
              </div>
            {% endif %}
            </div>
        </div>
      </div>
      <div class="study__content">
        {{ study.description|linebreaksbr }}
        <div class="study__content-joinContainer">
          {% if is_studying == 'joined' %}
            {% if study.user == request.user %}
              {% if  study.is_recruiting == 2 %}
                <button class="button-large" disabled>모집 마감</button>
                <a href="{% url 'studies:mainboard' study.pk %}" ><button class="button-large">메인보드</button></a>
                {% else %}
                <form id="condition-form" method="post" action="{% url 'studies:condition' study.pk 3 %}">
                    {% csrf_token %}
                    <button type="button" class="button-large" onClick="javascript:isComfirmJoin()">모집마감</button>
                </form>
              {% endif %}
              {% else %}
              <form action="{% url 'studies:withdraw' study.pk %}" method="post">
                {% csrf_token %}
                <button type"submit" class="button-large expel-btn">스터디 탈퇴</button>
              </form>
              <a href="{% url 'studies:mainboard' study.pk %}" ><button class="button-large">메인보드</button></a>
            {% endif %}
          {% elif is_studying == 'join_request' %}
            <form action="{% url 'studies:cancel' study.pk %}" method="post">
              {% csrf_token %}
              <button class="button-large" disabled>참여 요청 중</button>
              <button type="submit" class="button-large">참여 취소</button>
            </form>
          {% else %}
            {% if  study.is_recruiting == 2  %}
              <button class="button-large" disabled>모집 마감</button>
            {% else %}
              <form action="{% url 'studies:join' study.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="button-large">스터디 참여</button>
              </form>
            {% endif %}
            {% endif %}

        </div>
      </div>
    </div>
    <div class="category__container">
      {% for category in study.category.all|dictsort:'name' %}
      <a href="{% url 'studies:index' %}?category={{category}}">
        <span class="category-item">#{{ category }}</span>
      </a>
      {% endfor %}
    </div>
  </article>
  <hr />
  
  {# 댓글 #}
  <article>
    {# 댓글 작성 #}
    <form action="{% url 'studies:comment_create' study.pk %}" method="post" class="comment-create-form">
      {% csrf_token %}
      {{ comment_form.content }}
      <button type="submit" class="comment-btn button-small">댓글 작성</button>
    </form>
    <hr>

  {% for comment in comments reversed %}
  <div class="comment">
    <div class="comment-container">
      <div class="comment-header">
        <div class="comment-header-top">
          <p class="comment-user">{{ comment.user.emoji_username }}</p>
          <div class="comment-user-ud__container">
              {% if comment.user == request.user %}
              <form action="" class="comment-update-form" data-study-id="{{ study.pk }}" data-comment-id="{{ comment.pk }}">
                <button class="comment-update-btn" >
                  <i class="bi bi-pencil-fill"></i>
                </button>
              </form>
              <form action="{% url 'studies:comment_delete' study.pk comment.pk %}" method="post" class="comment-delete-form">
                {% csrf_token %}
                <button type="submit" class="comment-delete-btn">
                  <i class="bi bi-x-circle"></i>
                </button>
              </form>
              {% endif %}
          </div>         
          </div>
        <p class="comment-time">{{ comment.created_at_string }}</p>
      </div> 
      <div class="comment-body">
        <p id="comment-content-{{ comment.pk }}">{{ comment.content }}</p>
      </div>
    </div>
  </div>
  {% empty %}
  <p class="comment-empty">댓글이 없습니다.</p>
  {% endfor %}
  </article>
</main>

<script>
  function isComfirmJoin(){
    message = "모집을 마감하시겠습니까?";
    const confirmation = window.confirm(message);
  
    if (confirmation) {
      const form = document.getElementById('condition-form');
      form.submit();
    } else {
      return false
    }
  }

</script>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'JS/comment.js' %}"></script>


{% endblock content %}

studies/templates/studies/member.html
{% load static %} 
{% block style %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/studies/member.css' %}"
/>
{% endblock style %} 
{% block right_content %} 

{# 가입승인 스터디만 출력 #} 
{% if study.join_condition == 1 %}
<section>
  <h1 class="right_content-title">💓 가입 요청</h1>
  {% if join_requests %}
  {% for request in join_requests %}
    <div class="join-request__container">
        <div class="request-message">
          <span>{{request}}</span> 님께서 <span>{{study.title}}</span>에 참여를 요청하셨습니다.
        </div>
        <div class="request-btns__containers">
          <form action="{% url 'studies:accept' study.pk request %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button-small create-btn">승인</button>
          </form>
          <form action="{% url 'studies:reject' study.pk request %}" method="post">
            {% csrf_token %}
            <button type="submit" class="button-small create-btn">거절</button>
          </form>
        </div>
    </div>
    <hr>
  {% endfor %}
  {% else %}
  <div class="null-message">🐲 가입 요청이 없습니다!</div>
  {% endif %}
</section>
{% endif %}

{# 멤버 관리 #}
<section>
  <h1 class="right_content-title">
    🔎 멤버 관리
  <span class="member-capacity__container"> ( <span>{{ study_members.count }}</span> / {{study.capacity}} )</span>
  </h1>
  {% for member in study_members %}
  <div class="member__container">
    {% if member.permission == 3 %}
    <div class="member"> {{ member.user.emoji_username }} - </div>
    <div class="member-leader"> 스터디장</div>
    {% else %}
        <div>{{ member.user.emoji_username }}</div>
        <form action="{% url 'studies:expel' study.pk member.user %}" method="POST" onsubmit="return confirm('정말로 강퇴하시겠습니까?');">
        {% csrf_token %}
          <input type="submit" value="강퇴">
        </form>
    {% endif %}

  </div>
  {% endfor %}
</section>

<section>
  <h1 class="right_content-title">🔒 가입 조건 관리 </h1>
  <form id="condition-form" method="post" action="{% url 'studies:condition' study_pk=study.pk condition_num=0 %}">
    {% csrf_token %}
  
    <select id="condition-select" name="condition_num" data-condition="{{ study.join_condition }}" onchange="updateAction(this)">
      <option value="1" {% if study.join_condition == 1 %}selected{% endif %}>승인 필요</option>
      <option value="2" {% if study.join_condition == 2 %}selected{% endif %}>바로 가입</option>
      <option value="3" {% if study.join_condition == 3 %}selected{% endif %}>가입 불가</option>
    </select>
  
    <noscript>
      <input type="submit" value="조건 업데이트">
    </noscript>
  </form>
</section>


{% endblock right_content %}