accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path("<int:study_pk>/", views.room, name="room"),
    path("review/<int:review_pk>/", views.get_review_content, name="review"),
    
    path("<int:study_pk>/delete/", views.room_delete, name="room_delete"),
    
    # for fetch
    path("<int:study_pk>/problems/", views.problems, name="problems"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/", views.reviews, name="reviews"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/<int:review_pk>/", views.review_detail, name="review_detail"),
    ]

studies/urls.py
from django.urls import path
from . import views


app_name = 'studies'
urlpatterns = [
    # 스터디 CRUD
    path('', views.index, name='index'),
    path('<int:study_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:study_pk>/delete/', views.delete, name='delete'),
    path('<int:study_pk>/update/', views.update, name='update'),
    # 스터디 join_conditoin 변경
    path('<int:study_pk>/condition/<int:condition_num>/', views.condition, name='condition'),
    
    # 스터디 가입 요청 관련 {POST}
    path('<int:study_pk>/join/', views.join, name='join'), # 스터디 가입, 가입 요청
    path('<int:study_pk>/withdraw/', views.withdraw, name='withdraw'), # 스터디 탈퇴
    path('<int:study_pk>/accept/<username>/', views.accept, name='accept'), # 스터디 가입 요청 수락
    path('<int:study_pk>/reject/<username>/', views.reject, name='reject'), # 스터디 가입 요청 거절
    path('<int:study_pk>/expel/<username>/', views.expel, name='expel'), # 스터디원 방출
    path('<int:study_pk>/cancel/', views.cancel, name='cancel'), # 스터디 가입 요청 취소
  
    # 메인보드
    path('<int:study_pk>/mainboard/', views.mainboard, name='mainboard'),
    path('<int:study_pk>/mainboard/member/', views.member, name='member'),
    path('<int:study_pk>/mainboard/problem/', views.problem, name='problem'),
    path('<int:study_pk>/mainboard/problem/search/', views.problem_search, name='problem_search'),

    # 스터디 공지 in 메인보드
    path('<int:study_pk>/mainboard/announcement/', views.announcement, name='announcement'),
    path('<int:study_pk>/mainboard/announcement/create/', views.announcement_create, name='announcement_create'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/', views.announcement_detail, name='announcement_detail'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/update/', views.announcement_update, name='announcement_update'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/delete/', views.announcement_delete, name='announcement_delete'),
    
    # 스터디장 (Studying.permission) 임명(appoint), 해임(dismiss)
    # 부스터디장?
    path('<int:study_pk>/appoint/<username>/<int:permission>/', views.appoint, name='appoint'),
    path('<int:study_pk>/dismiss/<username>/', views.dismiss, name='dismiss'),
    
    # 스터디 댓글
    path('<int:study_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:study_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:study_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

emoji_dict = {
    0: '🥚',
    1: '🐣',
    2: '🐥',
    3: '🦎',
    4: '🦕',
    5: '🦖',
}

class User(AbstractUser):
    experience = models.PositiveIntegerField(default=0)

    def get_level(self):
        if self.experience >= 1000:
            return 5
        elif self.experience >= 500:
            return 4
        elif self.experience >= 200:
            return 3
        elif self.experience >= 90:
            return 2
        elif self.experience >= 30:
            return 1
        elif self.experience >= 0:
            return 0
        else:
            return ''

    def get_level(self):
        level = 0
        exp_thresholds = [0, 30, 90, 200, 500, 1000]
        
        for i, threshold in enumerate(exp_thresholds):
            if self.experience >= threshold:
                level = i
        
        return level
    
    def emoji_username(self):
        level = self.get_level()
        emoji = emoji_dict.get(level, '')
        return f'{emoji}{self.username}'

    def emoji(self):
        level = self.get_level()
        emoji = emoji_dict.get(level, '')
        return emoji
    
    def get_progress_percentage(self):
        level = self.get_level()
        current_exp = self.get_experience_from_level()
        next_level_exp = self.get_next_level_exp(level)
        
        if level == 5:
            return 100
        else:
            progress_percentage = (current_exp/ next_level_exp) * 100
            return int(progress_percentage)
        

    def get_experience_from_level(self):
        level = self.get_level()
        level_thresholds = [0, 30, 90, 200, 500, 1000]

        if level >= 0 and level < len(level_thresholds):
            current_level_exp = self.experience - level_thresholds[level]
            return current_level_exp if current_level_exp >= 0 else 0

        return 0


    def get_next_level_exp(self, level):
        exp_thresholds = [0, 30, 90, 200, 500, 1000]

        if level >= 0 and level < len(exp_thresholds) - 1:
            return exp_thresholds[level + 1] - exp_thresholds[level]

        return 0
    

    def get_total_experience_up_to_level(self, level):
        exp_thresholds = [0, 30, 90, 200, 500, 1000]

        if level >= 0 and level < len(exp_thresholds):
            return sum(exp_thresholds[:level+1])

        return 0
    
    def get_previous_emoji(self):
        level = self.get_level()
        previous_level = level - 1
        emoji = emoji_dict.get(previous_level, '')
        return emoji

    def get_next_emoji(self):
        level = self.get_level()
        next_level = level + 1
        emoji = emoji_dict.get(next_level, '')
        return emoji

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    labels = {
        'username': '이름',
        'email': '이메일',
        'password1': '비밀번호',
        'password2': '비밀번호 확인',
    }

    username = forms.CharField(
        label='이름',
        widget=forms.TextInput(attrs={'class': 'my-custom-class'})
    )
    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(attrs={'class': 'my-custom-class'})
    )
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(attrs={'class': 'my-custom-class'}),
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(attrs={'class': 'my-custom-class'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, label in self.labels.items():
            self.fields[field_name].label = label
            self.fields[field_name].help_text = ''
            self.fields[field_name].label_suffix = ''

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2',)


class CustomAuthenticationFormForm(AuthenticationForm):
    error_messages = {
        'invalid_login': '정확한 정보를 입력해주세요.',
    }
    class Meta:
        model = get_user_model()
        fields = ('username', 'password',)
        


class CustomUserChangeForm(UserChangeForm):
    labels = {
        'username': '이름',
        'email': '이메일',
    }

    username = forms.CharField(
        label='이름',
        widget=forms.TextInput(attrs={'class': 'my-custom-class'})
    )
    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(attrs={'class': 'my-custom-class'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = ''
            self.fields[field_name].label_suffix = ''
        self.fields['password'].help_text = ''

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('username', 'email',)


class CustomPasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].help_text = ''
            self.fields[field_name].label_suffix = ''

    class Meta(PasswordChangeForm):
        model = get_user_model()
        fields = ('old_password', 'new_password1', 'new_password2',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, Page
from django.http import JsonResponse
from django.db.models import Q

from .forms import CustomUserCreationForm, CustomAuthenticationFormForm, CustomUserChangeForm, CustomPasswordChangeForm
from studies.models import Study, Studying
from reviews.models import Review

# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('studies:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend',)
            
            prev_url = request.session.get('prev_url')
            # 이전 페이지의 URL 정보가 있으면 해당 URL로 리다이렉트합니다.
            if prev_url:
                # 이전 페이지의 URL 정보를 삭제합니다.
                del request.session['prev_url']
                return redirect(prev_url)
            
            return redirect('main')
    else:
        form = CustomUserCreationForm()
        
    # prev_url에 회원가입 페이지로 이동하기 이전 페이지 정보 기록 
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('studies:index')
    
    if request.method == 'POST':
        form = CustomAuthenticationFormForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            
            prev_url = request.session.get('prev_url')
            if prev_url:
                del request.session['prev_url']
                return redirect(prev_url)
            
            return redirect('main')
    else:
        form = CustomAuthenticationFormForm()
    
    request.session['prev_url'] = request.META.get('HTTP_REFERER')
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    # 작업 성공 후 이전 페이지로 이동
    prev_url = request.META.get('HTTP_REFERER')
    if prev_url:
        # 현재 프로필 페이지에 있다면 메인페이지로 이동
        if '/profile/' in prev_url:
            return redirect('main')
        return redirect(prev_url)
        
    return redirect('main')


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    
    return redirect('main')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('main')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            
            return redirect('main')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    query = request.GET.get('query')

    user = get_user_model()
    person = user.objects.get(username=username)
    host_studies = Study.objects.filter(user=person)
    guest_studies = Studying.objects.filter(user=person).exclude(study__in=host_studies)

    level = person.get_level()
    next_level_exp = person.get_next_level_exp(level)

    reviews = Review.objects.filter(user=person).order_by('-created_at')

    if query:
        reviews = reviews.filter(
            Q(problem__title__icontains=query) |
            Q(tags__name__icontains=query)
        ).distinct()

    # paginator = Paginator(reviews, 5) 
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    # reviews = page_obj.object_list

    context = {
        'person': person,
        'next_level_exp': next_level_exp,
        'host_studies': host_studies,
        'guest_studies': guest_studies,
        'reviews': reviews,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/accounts/change_password.css' %}"
  />
{% endblock style %}

{% block content %}
<div class="main__container">
  <div class="main__logobox">
    <p>제대로 STUDY</p>
  </div>
  <h1 class="main__title">비밀번호수정</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST" class="main__passwordbox">
    {% csrf_token %}
    <div>
      {{form.as_p}}
      <input type="submit" value="비밀번호변경" class="change-button">
    </div>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load static %}
{% block style %}
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/accounts/login.css' %}"
  />
{% endblock style %}
{% block content %}
    <div class="main__login-container">
      <div class="main__logobox">
        <p style="color: white;">제대로 STUDY</p>
      </div>
      <form action="{% url 'accounts:login' %}" method="POST" class="main__loginbox">
        {% csrf_token %}
        <div style="display:flex; flex-direction:column; align-items:center;">
          {{ form.as_p }}
          <input type="submit" value="로그인" class="main__loginbutton">
        </div>
      </form>
      <div class="main__socailbutton-container">
        <div>
          <p class="main__signupbutton-title">제대로 STUDY 계정이 없으신가요?</p>
          <a href="{% url 'accounts:signup' %}" class="main__signupbutton">제대로 STUDY 회원가입</a>
        </div>
        <div>
          <p class="main__signupbutton-title">비밀번호를 잊으셨나요?</p>
          <a href="{% url 'account_reset_password' %}" class="main__signupbutton">비밀번호 초기화</a>
        </div>
      </div>
    </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/accounts/profile.css' %}"
  />
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/card.css' %}"
  />
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/main.css' %}"
  />
{% endblock style %}
{% block content %}

<div class="main__title">
  <h1><span class="username-container" data-username={{person.username}}>{{ person.emoji_username }} </span>님의 프로필</h1>
</div>
<div class="main__wrapper">
  <aside class="aside__container">
    <div class="aside__item" data-section="profile">내 프로필</div>
    <div class="aside__item" data-section="study">내 스터디</div>
    <div class="aside__item" data-section="code">내 공부시간</div>
    <div class="aside__item" data-section="major">졸업요건</div>
  </aside>
  <section class="right-content__container">
    {% block right_content %}
    {% endblock right_content %}
    {#내 프로필#}
    <section class="right_content-item__wrapper">
      <div>
        <h1 class="profile-title">🔗 회원정보</h1>
        <div class="profile-id"><span class="profile-id1">아이디 </span>{{ person.username }}</div>
        <div class="profile-email"><span class="profile-email1">이메일 </span>{{ person.email }}</div>
        <div class=" profile-exp">
          <p class="profile-exp1">내 레벨</p>
          <div class="progress-container">
            {% if person.get_previous_emoji %}
              <span class="emoji">{{ person.get_previous_emoji }}</span>
            {% endif %}
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ person.get_progress_percentage }}%"></div>
              <div class="progress-text">
                <p>EXP {{ person.get_progress_percentage }}% ({{ person.get_experience_from_level }} / {{ next_level_exp }})</p>
              </div>
            </div>
            {% if person.get_next_emoji %}
              <span class="emoji">{{ person.get_next_emoji }}</span>
            {% endif %}
          </div>
          <p>LV. {{ person.get_level }} {{person.emoji}}</p>
        </div>
        <div class="button-box">
          <a href="{% url 'accounts:update' %}"><div class="create-btn button-small">회원정보수정</div></a>
          <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴" class="create-btn button-small">
          </form>
        </div>
      </div>      
    </section>
    {#내 스터디#}
    <section class="right_content-item__wrapper">
      <div>
        <h1 class="profile-title">📤 내가 주최한 스터디</h1>
        <div>
          {% if host_studies  %}
          <section class="myStudies__container">
            <div class="newStudies__wrapper">
              {% for host_study in host_studies %}
              <div class="newStudies__container">
                {% if host_study.announcements_count %}
                  <div class="alarm blinking">
                    {{ host_study.announcements_count }}
                  </div>
                {% endif %}
                <div class="newStudies-title card__title">{{ host_study.title }}</div>
                <div class="card__days-container">
                  {% for day in host_study.days %} 
                  <div class="card__day">{{ day }}</div>
                  {% endfor %}
                </div>
                <div class="card__language-container">
                  {% for language  in host_study.language %}
                  <div class="card__language">
                    <p>{{ language }}</p>
                  </div>
                  {% endfor %}
                </div>
                <div class="newStudies-joinbutton__container">
                  <a href="{% url 'studies:mainboard' host_study.pk %}">
                    <button class="button-small joinbutton">입장 하기</button>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>   
          </section>
        {% endif %}
        </div>
      </div>
      <div>
        <h1 class="profile-title">📥 내가 가입한 스터디</h1>
        <div>
          {% if guest_studies %}
          <section class="myStudies__container">
            <div class="newStudies__wrapper">
              {% for guest_study in guest_studies %}
              <div class="newStudies__container">
                {% if guest_study.announcements_count %}
                  <div class="alarm blinking">
                    {{ guest_study.announcements_count }}
                  </div>
                {% endif %}
                <div class="newStudies-title card__title">{{ guest_study.study.title }}</div>
                <div class="card__days-container">
                  {% for day in guest_study.study.days %} 
                  <div class="card__day">{{ day }}</div>
                  {% endfor %}
                </div>
                <div class="card__language-container">
                  {% for language  in guest_study.study.language %}
                  <div class="card__language">
                    <p>{{ language }}</p>
                  </div>
                  {% endfor %}
                </div>
                <div class="newStudies-joinbutton__container">
                  <a href="{% url 'studies:mainboard' guest_study.study.pk %}">
                    <button class="button-small joinbutton">입장 하기</button>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>   
          </section>
        {% endif %}
        </div>
      </div> 
    </section>
    {#내 코드 모음#}
    <section class="right_content-item__wrapper">
      <div class="review-top__box">
        <h1 class="profile-title profile-data" data-username="{{person.username}}">📝 내 공부시간</h1>
      </div>

      <iframe width="475" height="250" src="https://vclock.kr/embed/stopwatch/#theme=0" frameborder="0" allowfullscreen></iframe>
      <!-- 페이지네이션 컨테이너 -->
      
    </section>
    <section class="right_content-item__wrapper">
      <div class="review-top__box">
        <h1 class="profile-title">📝 우리학과 졸업요건</h1>
      </div>
      <!-- 페이지네이션 컨테이너 -->
      <div class="pagination-container"></div>
      
    </section>
  </section>
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'JS/profile.js' %}?after"></script>
<script src="{% static 'JS/profile-search.js' %}"></script>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
<!-- 기본 회원가입 템플릿 -->

{% load socialaccount %}
{% load static %}

{% block style %}
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/accounts/signup.css' %}"
  />
{% endblock style %}


{% block content %}
    <div class="main__signup-container">
      <div class="main__logobox">
        <p style="color: white;">제대로 STUDY</p>
      </div>
      <form action="{% url 'accounts:signup' %}" method="POST" class="main__signupbox">
        {% csrf_token %}
        <div>
          {{ form.as_p }}
          <input type="submit" value="altudy 회원가입" class="main__signupbutton">
        </div>
      </form>
    </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/accounts/update.css' %}"
  />
{% endblock style %}
{% block content %}
<div class="main__container">
  <div class="main__logobox">
    <p>제대로 STUDY</p>
  </div>
  <form action="{% url 'accounts:update' %}" method="POST" class="main__updatebox">
    {% csrf_token %}
    <div>
      <p>
        <label for="id_username">이름</label>
        {{ form.username }}
      </p>
      <p>
        <label for="id_email">이메일</label>
        {{ form.email }}
      </p>
      <div>
        <input type="submit" value="회원정보수정" class="update-button">
      </div>
      <div class="password-button-border">
        <a href="{% url 'accounts:change_password' %}" class="password-button">비밀번호 변경하기</a>
      </div>
    </div>
  </form>
</div>
{% endblock content %}