accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path("<int:study_pk>/", views.room, name="room"),
    path("review/<int:review_pk>/", views.get_review_content, name="review"),
    
    path("<int:study_pk>/delete/", views.room_delete, name="room_delete"),
    
    # for fetch
    path("<int:study_pk>/problems/", views.problems, name="problems"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/", views.reviews, name="reviews"),
    path("<int:study_pk>/problems/<int:problem_pk>/reviews/<int:review_pk>/", views.review_detail, name="review_detail"),
    ]

studies/urls.py
from django.urls import path
from . import views


app_name = 'studies'
urlpatterns = [
    # 스터디 CRUD
    path('', views.index, name='index'),
    path('<int:study_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:study_pk>/delete/', views.delete, name='delete'),
    path('<int:study_pk>/update/', views.update, name='update'),
    # 스터디 join_conditoin 변경
    path('<int:study_pk>/condition/<int:condition_num>/', views.condition, name='condition'),
    
    # 스터디 가입 요청 관련 {POST}
    path('<int:study_pk>/join/', views.join, name='join'), # 스터디 가입, 가입 요청
    path('<int:study_pk>/withdraw/', views.withdraw, name='withdraw'), # 스터디 탈퇴
    path('<int:study_pk>/accept/<username>/', views.accept, name='accept'), # 스터디 가입 요청 수락
    path('<int:study_pk>/reject/<username>/', views.reject, name='reject'), # 스터디 가입 요청 거절
    path('<int:study_pk>/expel/<username>/', views.expel, name='expel'), # 스터디원 방출
    path('<int:study_pk>/cancel/', views.cancel, name='cancel'), # 스터디 가입 요청 취소
  
    # 메인보드
    path('<int:study_pk>/mainboard/', views.mainboard, name='mainboard'),
    path('<int:study_pk>/mainboard/member/', views.member, name='member'),
    path('<int:study_pk>/mainboard/problem/', views.problem, name='problem'),
    path('<int:study_pk>/mainboard/problem/search/', views.problem_search, name='problem_search'),

    # 스터디 공지 in 메인보드
    path('<int:study_pk>/mainboard/announcement/', views.announcement, name='announcement'),
    path('<int:study_pk>/mainboard/announcement/create/', views.announcement_create, name='announcement_create'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/', views.announcement_detail, name='announcement_detail'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/update/', views.announcement_update, name='announcement_update'),
    path('<int:study_pk>/mainboard/announcement/<int:announcement_pk>/delete/', views.announcement_delete, name='announcement_delete'),
    
    # 스터디장 (Studying.permission) 임명(appoint), 해임(dismiss)
    # 부스터디장?
    path('<int:study_pk>/appoint/<username>/<int:permission>/', views.appoint, name='appoint'),
    path('<int:study_pk>/dismiss/<username>/', views.dismiss, name='dismiss'),
    
    # 스터디 댓글
    path('<int:study_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:study_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:study_pk>/comment/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
]

templates/base.html
{% load static %}
{% load studies_tags %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>
    제대로스터디 {% block title %}
    {% endblock title %}
  </title>
  <link rel="shortcut icon" href="{% static 'IMAGE/altudy.png' %}" type="image/x-icon">

  {% block head %}
  {% endblock head %}
  {# Bootstrap #}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  
  {# ToastUI #}
  <link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css" />

  {# 폰트 #}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">

  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/reset.css' %}"
  />
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/common.css' %}"
  />
  <link
  rel="stylesheet"
  type="text/css"
  href="{% static 'CSS/base.css' %}"
  />

  {% block style %}
  {% endblock style %}

</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <header class="header_nav">
    <nav>
      <div class="nav__container">
        <div class="nav__container-left">
          <a href="{% url 'main' %}">
            제대로 STUDY
          </a>
          </div>
        <div class="nav__container-right">
          <form action="{% url 'studies:index' %}" class="nav__search" role="search">
            <input class="nav__search-input" type="text" placeholder="스터디를 검색해보세요!" aria-label="Search" name="query" value="{{request.GET.query}}">
            <button class="nav__search-button" type="submit">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
              </svg>
            </button>
          </form>
          {% if user.is_authenticated %}
            <div class="nav__item dropdown">
              <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                알림
                {% if request.user|alarm_exists %}
                <div class="alarm-icon"></div>
                {% endif %}
              </button>
              <ul class="dropdown-menu">
                <div class="dropdown-menu-title">
                  📢 내 알림
                </div>

                {% if not requests_exist and not announcements_exist %}
                  <p class="dropdown-menu__no-message">알림 없음</p>
                {% endif %}

                {% if requests_exist %}
                <li><hr class="dropdown-divider"></li>
                <h2>💓 스터디 가입 요청</h2>
                <div class="dropdown-menu__container">
                  {% for study_requests in all_requests %}
                  {% with study_requests|first as study %}
                    {% for request in study_requests|last %}
                      <div class="content-box">
                        <a href="{% url 'studies:mainboard' study.pk %}">
                          <div class="join-message"> <span class="dropdown-menu__study">{{ study.title }}</span> - <span class="username">{{ request }}</span></div>
                          <div class="button-box">
                        </a>
                          <form action="{% url 'studies:accept' study.pk request %}" method="post">
                            {% csrf_token %}
                            <button class="create-btn button-small" type="submit">승인</button>
                          </form>
                          <form action="{% url 'studies:reject' study.pk request %}" method="post">
                            {% csrf_token %}
                            <button class="create-btn button-small" type="submit">거절</button>
                          </form>
                        </div>
                      </div>
                    {% endfor %}
                  {% endwith %}
                  {% endfor %}
                </div>
                {% endif %}

                {% if announcements_exist %}
                <hr>
                <h2>📌 공지사항</h2>
                
                <div class="dropdown-menu__container">

                  {% for study_announcements in all_announcements %}
                  {% with study_announcements|first as study %}
                  {% if study_announcements|last %}
                  <div class="announcement-item">
                    <p class="dropdown-menu__study">{{ study.title }}</p>
                    {% for announcement in study_announcements|last %}
                    <a href="{% url 'studies:announcement_detail' announcement.study.pk announcement.pk %}">
                      <div class="announcement-title">👉 {{ announcement.title }}</div>
                    </a>
                    {% endfor %}
                  </div>
                    {% endif %}
                    {% endwith %}
                  {% endfor %}
                </div>
                {% endif %}
                <hr>
              </ul>
            </div>
            <a href="{% url 'accounts:profile' request.user %}">
              <div class="nav__item">내 프로필</div>
            </a>
            <a href="{% url 'accounts:logout' %}">
              <div class="nav__item">로그아웃</div>
            </a>
          {% else %}
            <a href="{% url 'accounts:login' %}">
              <div class="nav__item">로그인</div>
            </a>
            <a href="{% url 'accounts:signup' %}">
              <div class="nav__item">회원가입</div>
            </a>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <main>
    {% block content %}
    {% endblock content %}
  </main>

  <footer>
    <div class="footer__container">
      <div>
        <span>&copy; <a href="">제대로스터디</a></span>
        <span>| multi-campus KDT 2th Final-project |&nbsp</span>
      </div>
      <div class="teamInfo">
        <a href=""></a>        
        <a href=""></a>
        <a href=""></a>
        <a href=""></a>
        <a href=""></a>
      </div>
    </div>
  </footer>

  {# Bootstrap #}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  
  {# ToastUI #}
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
  <script src="https://uicdn.toast.com/editor-plugin-code-syntax-highlight/latest/toastui-editor-plugin-code-syntax-highlight-all.min.js"></script>


  {# htmx #}
  <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>


  

  {% comment %} <script>
    fetch('/alarm')
      .then(response => response.json())
      .then(data => {
        console.log(data)
      })
      .catch(error => {
        console.error('Error:', error);
      });
  </script> {% endcomment %}

</body>

</html>

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
  <link rel="stylesheet" type="text/css" href="{% static 'CSS/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'CSS/card.css' %}" />
{% endblock style %}
{% block content %}
<main id="main__main">
  <a href="{% url 'studies:create' %}">
    <svg class="study-create-button" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
    </svg>
  </a>
  

  {# 최신 스터디 #}
  <section>
    <div class="studies__title">최신 스터디 👩‍🏫</div>
  </section>
  {# 모든 스터디 #}
  <section>
    <div class="all-box">
      <p>새로운 스터디에 도전하고 싶으신가요?</p>
      <p><a href="{% url 'studies:index' %}" class="a"><b>버튼</b></a>을 클릭하면 더 많은 스터디를 찾아볼 수 있습니다.</p>
      <a href="{% url 'studies:index' %}">
        <button class="btn button-small">더 많은 스터디 보러가기 ></button>
      </a>
    </div>
  </section>
</main>
{% endblock content %}